name: Build and Release Rust (SemVer Auto)

on:
  push:
    branches: ["w1"]
    paths: ["buildz/**"]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository (with tags)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for git tag history

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Build Release
        working-directory: ./buildz/w1
        run: cargo build --release

      - name: Determine SemVer Bump Level
        id: semver
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"[major]"* ]]; then
            echo "bump_level=major" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event.head_commit.message }}" == *"[minor]"* ]]; then
            echo "bump_level=minor" >> $GITHUB_OUTPUT
          else
            echo "bump_level=patch" >> $GITHUB_OUTPUT
          fi

      - name: Get Current Version
        id: current_version
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "current_version=${LATEST_TAG}" >> $GITHUB_OUTPUT

      - name: Bump Version
        id: bump
        uses: cbrgm/semver-bump-action@main
        with:
          current-version: ${{ steps.current_version.outputs.current_version }}
          bump-level: ${{ steps.semver.outputs.bump_level }}

      - name: Create Tag
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git tag ${{ steps.bump.outputs.new_version }}
          git push origin ${{ steps.bump.outputs.new_version }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.bump.outputs.new_version }}
          name: "Release ${{ steps.bump.outputs.new_version }}"
          files: buildz/w1/target/release/pantismyl
          generate_release_notes: true
