name: Build and Release Rust (SemVer Auto)

on:
  push:
    branches: ["w1"]
    paths: ["buildz/**"]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build Release
        working-directory: ./buildz/w1
        run: cargo build --release

      - name: Determine Next Version
        id: version
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          VERSION=${LATEST_TAG#v}
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
          NEXT_TAG="v${MAJOR}.${MINOR}.$((PATCH + 1))"
          echo "next_tag=${NEXT_TAG}" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.next_tag }}
          files: buildz/w1/target/release/pantismyl
#####################################################
#Version Bumping:
#
# Major: Triggered if commit message contains [major].
#
# Minor: Triggered if commit message contains [minor].
#
#Patch: Default increment (e.g., v1.0.0 → v1.0.1).
